# http://localhost:8080/actuator/gateway/routes
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: goodsapigateway
  cloud:
    # A client sends a request to Spring Cloud Gateway. If the request matches a route through its predicates, the Gateway HandlerMapping will send the request to the Gateway WebHandler, which in turn will run the request through a chain of filters.
    gateway:
      # For automatic route discovery through Eureka
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      # Route. It’s identified by a unique ID, a collection of predicates deciding whether to follow the route, a URI for forwarding the request if the predicates allow, and a collection of filters applied either before or after forwarding the request downstream.
      routes:
        - id: accountmsmodule
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<path>.*), /$\{path}
        - id: ordermsmodule
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}
        - id: catalogmsmodule
          uri: lb://catalog
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/(?<path>.*), /$\{path}
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.edu: DEBUG